"""
memory/services/memory_service.py

Memory Service

High-level memory lifecycle operations.

Responsibilities
----------------
- Conversation memory
- Execution memory
- Session memory
- Automatic routing
- Memory creation helpers

This service sits above the individual memory stores and
uses MemoryManager as the unified storage interface.
"""

from __future__ import annotations

import logging
from datetime import datetime
from typing import Any, Dict, Iterable, List, Optional

from app.memory.manager import MemoryManager
from app.memory.models.memory import Memory, MemoryType

logger = logging.getLogger(__name__)


class MemoryService:
    """
    High-level memory service.

    Responsible for creating, storing and managing
    memories generated by the application.

    Unlike MemoryManager, this class does not directly
    interact with memory stores. Instead it delegates
    persistence to MemoryManager.
    """

    # ---------------------------------------------------------
    # Initialization
    # ---------------------------------------------------------

    def __init__(
        self,
        manager: MemoryManager,
    ) -> None:

        self.manager = manager

        logger.info("MemoryService initialized.")

    # =========================================================
    # Memory Creation
    # =========================================================

    def _create_memory(
        self,
        *,
        memory_type: MemoryType,
        content: str,
        importance: float = 0.5,
        metadata: Optional[Dict[str, Any]] = None,
    ) -> Memory:
        """
        Create a memory object.

        Every helper eventually routes through here.
        """

        metadata = metadata or {}

        metadata.setdefault(
            "created_at",
            datetime.utcnow().isoformat(),
        )

        return Memory(
            memory_type=memory_type,
            content=content,
            importance=importance,
            metadata=metadata,
        )

    # =========================================================
    # Conversation Memory
    # =========================================================

    def remember_message(
        self,
        role: str,
        message: str,
        importance: float = 0.4,
        metadata: Optional[Dict[str, Any]] = None,
    ) -> Memory:
        """
        Store a single conversation message
        in Working Memory.
        """

        memory = self._create_memory(
            memory_type=MemoryType.WORKING,
            content=f"{role}: {message}",
            importance=importance,
            metadata=metadata,
        )

        self.manager.add(memory)

        logger.debug(
            "Stored conversation message (%s).",
            role,
        )

        return memory

    def remember_messages(
        self,
        messages: Iterable[Dict[str, Any]],
        importance: float = 0.4,
    ) -> List[Memory]:
        """
        Store multiple chat messages.
        """

        stored: List[Memory] = []

        for message in messages:

            memory = self.remember_message(
                role=message.get("role", "user"),
                message=message.get("content", ""),
                importance=importance,
                metadata=message.get("metadata"),
            )

            stored.append(memory)

        return stored

    def remember_conversation(
        self,
        conversation: List[Dict[str, Any]],
        summary: Optional[str] = None,
        importance: float = 0.7,
        metadata: Optional[Dict[str, Any]] = None,
    ) -> Memory:
        """
        Store an entire conversation as
        episodic memory.
        """

        if summary is None:

            lines = []

            for msg in conversation:

                role = msg.get("role", "user")
                content = msg.get("content", "")

                lines.append(
                    f"{role}: {content}"
                )

            summary = "\n".join(lines)

        memory = self._create_memory(
            memory_type=MemoryType.EPISODIC,
            content=summary,
            importance=importance,
            metadata=metadata,
        )

        self.manager.add(memory)

        logger.info(
            "Conversation stored as episodic memory."
        )

        return memory

    def remember_session(
        self,
        session_id: str,
        summary: str,
        metadata: Optional[Dict[str, Any]] = None,
    ) -> Memory:
        """
        Store a completed user session.
        """

        metadata = metadata or {}

        metadata["session_id"] = session_id

        memory = self._create_memory(
            memory_type=MemoryType.EPISODIC,
            content=summary,
            importance=0.8,
            metadata=metadata,
        )

        self.manager.add(memory)

        logger.info(
            "Session %s stored.",
            session_id,
        )

        return memory

    # =========================================================
    # Execution Memory
    # =========================================================

    def remember_execution(
        self,
        task: str,
        result: str,
        success: bool = True,
        importance: float = 0.8,
        metadata: Optional[Dict[str, Any]] = None,
    ) -> Memory:
        """
        Store execution result.
        """

        metadata = metadata or {}

        metadata.update(
            {
                "task": task,
                "success": success,
                "type": "execution",
            }
        )

        content = (
            f"Task:\n{task}\n\n"
            f"Success: {success}\n\n"
            f"Result:\n{result}"
        )

        memory = self._create_memory(
            memory_type=MemoryType.EPISODIC,
            content=content,
            importance=importance,
            metadata=metadata,
        )

        self.manager.add(memory)

        logger.info(
            "Execution remembered."
        )

        return memory

    def remember_plan(
        self,
        objective: str,
        steps: Iterable[str],
        metadata: Optional[Dict[str, Any]] = None,
    ) -> Memory:
        """
        Store an execution plan.
        """

        text = "\n".join(
            f"{i+1}. {step}"
            for i, step in enumerate(steps)
        )

        memory = self._create_memory(
            memory_type=MemoryType.PROCEDURAL,
            content=(
                f"Objective:\n{objective}\n\n"
                f"Plan:\n{text}"
            ),
            importance=0.75,
            metadata=metadata,
        )

        self.manager.add(memory)

        logger.info(
            "Execution plan remembered."
        )

        return memory

    def remember_tool_use(
        self,
        tool_name: str,
        input_text: str,
        output_text: str,
        success: bool = True,
        metadata: Optional[Dict[str, Any]] = None,
    ) -> Memory:
        """
        Store tool usage history.
        """

        metadata = metadata or {}

        metadata.update(
            {
                "tool": tool_name,
                "success": success,
            }
        )

        content = (
            f"Tool: {tool_name}\n\n"
            f"Input:\n{input_text}\n\n"
            f"Output:\n{output_text}"
        )

        memory = self._create_memory(
            memory_type=MemoryType.EPISODIC,
            content=content,
            importance=0.6,
            metadata=metadata,
        )

        self.manager.add(memory)

        logger.debug(
            "Tool usage stored (%s).",
            tool_name,
        )

        return memory

    def remember_fact(
        self,
        fact: str,
        importance: float = 0.9,
        metadata: Optional[Dict[str, Any]] = None,
    ) -> Memory:
        """
        Store semantic knowledge.
        """

        memory = self._create_memory(
            memory_type=MemoryType.SEMANTIC,
            content=fact,
            importance=importance,
            metadata=metadata,
        )

        self.manager.add(memory)

        return memory

    def remember_procedure(
        self,
        procedure: str,
        importance: float = 0.8,
        metadata: Optional[Dict[str, Any]] = None,
    ) -> Memory:
        """
        Store procedural knowledge.
        """

        memory = self._create_memory(
            memory_type=MemoryType.PROCEDURAL,
            content=procedure,
            importance=importance,
            metadata=metadata,
        )

        self.manager.add(memory)

        return memory

    def remember_research(
        self,
        research: str,
        importance: float = 0.8,
        metadata: Optional[Dict[str, Any]] = None,
    ) -> Memory:
        """
        Store research findings.
        """

        memory = self._create_memory(
            memory_type=MemoryType.RESEARCH,
            content=research,
            importance=importance,
            metadata=metadata,
        )

        self.manager.add(memory)

        return memory
    
        # =========================================================
    # Working Memory Lifecycle
    # =========================================================

    def push_working_memory(
        self,
        content: str,
        importance: float = 0.5,
        metadata: Optional[Dict[str, Any]] = None,
    ) -> Memory:
        """
        Push information into working memory.
        """

        memory = self._create_memory(
            memory_type=MemoryType.WORKING,
            content=content,
            importance=importance,
            metadata=metadata,
        )

        self.manager.add(memory)

        logger.debug("Added item to working memory.")

        return memory

    def push_working_memories(
        self,
        contents: Iterable[str],
        importance: float = 0.5,
    ) -> List[Memory]:
        """
        Store multiple working memories.
        """

        memories = []

        for content in contents:
            memories.append(
                self.push_working_memory(
                    content=content,
                    importance=importance,
                )
            )

        return memories

    def clear_working_memory(self) -> None:
        """
        Clear the working memory store.
        """

        logger.info("Clearing working memory.")

        self.manager.working_memory.clear()

    def expire_working_memory(
        self,
        max_items: int = 50,
    ) -> int:
        """
        Trim working memory to the most
        recent items.

        Returns
        -------
        int
            Number of removed memories.
        """

        store = self.manager.working_memory

        if not hasattr(store, "memories"):
            return 0

        memories = store.memories

        if len(memories) <= max_items:
            return 0

        removed = len(memories) - max_items

        store.memories = memories[-max_items:]

        logger.info(
            "Expired %d working memories.",
            removed,
        )

        return removed

    def refresh_working_memory(self) -> None:
        """
        Remove stale working memories.

        This is intended to be called
        periodically by the execution engine.
        """

        self.expire_working_memory()

    # =========================================================
    # Consolidation
    # =========================================================

    def consolidate(self) -> Dict[str, int]:
        """
        Consolidate memories.

        High-importance working memories are
        promoted into long-term memory.
        """

        promoted_semantic = 0
        promoted_procedural = 0
        archived = 0

        working_store = self.manager.working_memory

        if not hasattr(working_store, "memories"):
            return {
                "semantic": 0,
                "procedural": 0,
                "archived": 0,
            }

        for memory in list(working_store.memories):

            importance = getattr(
                memory,
                "importance",
                0.0,
            )

            if importance < 0.75:
                continue

            text = memory.content.lower()

            if any(
                word in text
                for word in (
                    "how",
                    "procedure",
                    "step",
                    "algorithm",
                    "workflow",
                    "process",
                    "install",
                )
            ):

                self.promote_to_procedural(memory)
                promoted_procedural += 1

            else:

                self.promote_to_semantic(memory)
                promoted_semantic += 1

            self.archive(memory)
            archived += 1

        logger.info(
            "Consolidation completed."
        )

        return {
            "semantic": promoted_semantic,
            "procedural": promoted_procedural,
            "archived": archived,
        }

    # =========================================================
    # Promotion
    # =========================================================

    def promote_to_semantic(
        self,
        memory: Memory,
    ) -> Memory:
        """
        Promote a memory into semantic memory.
        """

        promoted = self._create_memory(
            memory_type=MemoryType.SEMANTIC,
            content=memory.content,
            importance=max(
                getattr(memory, "importance", 0.5),
                0.8,
            ),
            metadata=dict(
                getattr(memory, "metadata", {})
            ),
        )

        promoted.metadata["source"] = "working"

        self.manager.add(promoted)

        logger.debug(
            "Promoted memory to semantic."
        )

        return promoted

    def promote_to_procedural(
        self,
        memory: Memory,
    ) -> Memory:
        """
        Promote a memory into procedural memory.
        """

        promoted = self._create_memory(
            memory_type=MemoryType.PROCEDURAL,
            content=memory.content,
            importance=max(
                getattr(memory, "importance", 0.5),
                0.8,
            ),
            metadata=dict(
                getattr(memory, "metadata", {})
            ),
        )

        promoted.metadata["source"] = "working"

        self.manager.add(promoted)

        logger.debug(
            "Promoted memory to procedural."
        )

        return promoted

    # =========================================================
    # Archiving
    # =========================================================

    def archive(
        self,
        memory: Memory,
    ) -> None:
        """
        Archive a working memory.

        Default behaviour:
            remove it from working memory.

        Future versions may move it into
        an archive store.
        """

        try:

            self.manager.remove(memory)

        except Exception:

            logger.exception(
                "Failed to archive memory."
            )

    def archive_many(
        self,
        memories: Iterable[Memory],
    ) -> int:
        """
        Archive multiple memories.
        """

        count = 0

        for memory in memories:

            self.archive(memory)
            count += 1

        logger.info(
            "Archived %d memories.",
            count,
        )

        return count

    def archive_all_working_memory(self) -> int:
        """
        Archive every working memory.

        Useful when ending a conversation
        or shutting down the agent.
        """

        store = self.manager.working_memory

        if not hasattr(store, "memories"):
            return 0

        memories = list(store.memories)

        self.archive_many(memories)

        return len(memories)
        # =========================================================
    # Maintenance
    # =========================================================

    def cleanup(
        self,
    ) -> Dict[str, int]:
        """
        Run maintenance across all memory stores.

        Returns
        -------
        Dict[str, int]
            Number of cleaned memories.
        """

        cleaned = {}

        for memory_type, store in self.manager._stores.items():

            if hasattr(store, "cleanup"):

                try:

                    cleaned[memory_type.value] = (
                        store.cleanup()
                    )

                except Exception:

                    logger.exception(
                        "Cleanup failed for %s",
                        memory_type.value,
                    )

                    cleaned[memory_type.value] = 0

            else:

                cleaned[memory_type.value] = 0

        logger.info("Memory cleanup completed.")

        return cleaned

    def deduplicate(
        self,
    ) -> Dict[str, int]:
        """
        Remove duplicate memories.

        Duplicate detection is based on
        normalized memory content.
        """

        removed = {}

        for memory_type, store in self.manager._stores.items():

            if not hasattr(store, "memories"):
                removed[memory_type.value] = 0
                continue

            seen = set()

            unique = []

            duplicates = 0

            for memory in store.memories:

                key = memory.content.strip().lower()

                if key in seen:
                    duplicates += 1
                    continue

                seen.add(key)
                unique.append(memory)

            store.memories = unique

            removed[memory_type.value] = duplicates

        logger.info(
            "Deduplication finished."
        )

        return removed

    def prune(
        self,
        importance_threshold: float = 0.20,
    ) -> Dict[str, int]:
        """
        Remove low-importance memories.
        """

        removed = {}

        for memory_type, store in self.manager._stores.items():

            if not hasattr(store, "memories"):
                removed[memory_type.value] = 0
                continue

            before = len(store.memories)

            store.memories = [

                m

                for m in store.memories

                if getattr(
                    m,
                    "importance",
                    0.0,
                ) >= importance_threshold

            ]

            removed[memory_type.value] = (

                before - len(store.memories)

            )

        logger.info(
            "Pruning completed."
        )

        return removed

    def decay_importance(
        self,
        decay: float = 0.98,
    ) -> int:
        """
        Apply importance decay.

        Called periodically to slowly
        reduce importance of stale memories.
        """

        updated = 0

        for _, store in self.manager._stores.items():

            if not hasattr(store, "memories"):
                continue

            for memory in store.memories:

                if hasattr(memory, "importance"):

                    memory.importance *= decay

                    updated += 1

        logger.info(
            "Importance decay applied."
        )

        return updated

    def maintenance(
        self,
    ) -> Dict[str, Any]:
        """
        Run the complete maintenance pipeline.
        """

        return {

            "cleanup": self.cleanup(),

            "deduplicate": self.deduplicate(),

            "prune": self.prune(),

            "decay": self.decay_importance(),

        }

    # =========================================================
    # Statistics
    # =========================================================

    def statistics(
        self,
    ) -> Dict[str, Any]:
        """
        Return statistics for all stores.
        """

        return self.manager.stats()

    def health(
        self,
    ) -> Dict[str, Any]:
        """
        Memory system health.
        """

        stats = self.statistics()

        total = sum(stats.values())

        return {

            "healthy": total >= 0,

            "total_memories": total,

            "stores": stats,

        }

    def summary(
        self,
    ) -> Dict[str, Any]:
        """
        Overall memory summary.
        """

        stats = self.statistics()

        return {

            "statistics": stats,

            "health": self.health(),

            "working_items": stats.get(
                "working",
                0,
            ),

            "long_term_items": (

                stats.get("semantic", 0)
                + stats.get("episodic", 0)
                + stats.get("procedural", 0)
                + stats.get("research", 0)

            ),

        }

    # =========================================================
    # Async Wrappers
    # =========================================================

    async def async_remember_message(
        self,
        *args,
        **kwargs,
    ) -> Memory:
        """
        Async wrapper.
        """

        return self.remember_message(
            *args,
            **kwargs,
        )

    async def async_remember_execution(
        self,
        *args,
        **kwargs,
    ) -> Memory:

        return self.remember_execution(
            *args,
            **kwargs,
        )

    async def async_remember_conversation(
        self,
        *args,
        **kwargs,
    ) -> Memory:

        return self.remember_conversation(
            *args,
            **kwargs,
        )

    async def async_consolidate(
        self,
    ) -> Dict[str, int]:

        return self.consolidate()

    async def async_cleanup(
        self,
    ) -> Dict[str, int]:

        return self.cleanup()

    async def async_maintenance(
        self,
    ) -> Dict[str, Any]:

        return self.maintenance()

    async def async_statistics(
        self,
    ) -> Dict[str, Any]:

        return self.statistics()

    async def async_health(
        self,
    ) -> Dict[str, Any]:

        return self.health()

    # =========================================================
    # Utility
    # =========================================================

    def __len__(
        self,
    ) -> int:
        """
        Total memories.
        """

        return sum(
            self.statistics().values()
        )

    def __repr__(
        self,
    ) -> str:

        stats = self.statistics()

        return (
            f"{self.__class__.__name__}("
            f"working={stats.get('working',0)}, "
            f"semantic={stats.get('semantic',0)}, "
            f"episodic={stats.get('episodic',0)}, "
            f"procedural={stats.get('procedural',0)}, "
            f"research={stats.get('research',0)})"
        )