"""
schemas.py

Definitions for AI tools.

Every tool exposed to the agent is represented by
a ToolSchema.
"""

from __future__ import annotations

from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class ToolParameter(BaseModel):
    """
    Single parameter accepted by a tool.
    """

    name: str
    type: str
    description: str
    required: bool = True


class ToolSchema(BaseModel):
    """
    Metadata describing a tool.
    """

    name: str
    description: str

    parameters: List[ToolParameter] = Field(default_factory=list)

    returns: str = "Any"

    version: str = "1.0"

    tags: List[str] = Field(default_factory=list)


class ToolCall(BaseModel):
    """
    A request generated by the LLM.
    """

    tool_name: str

    arguments: Dict[str, Any] = Field(default_factory=dict)


class ToolResult(BaseModel):
    """
    Result returned by a tool.
    """

    tool_name: str

    success: bool

    output: Any = None

    error: Optional[str] = None