from __future__ import annotations

from dataclasses import dataclass, field
from typing import List, Dict, Any, Optional



@dataclass
class AnalystArgument:
    """
    Represents an individual analyst opinion
    during investment committee debate.
    """

    role: str

    position: str

    supporting_points: List[str] = field(
        default_factory=list
    )

    concerns: List[str] = field(
        default_factory=list
    )

    confidence: float = 0.0



@dataclass
class AnalystVote:
    """
    Represents analyst voting decision.
    """

    analyst: str

    vote: str

    reasoning: str = ""

    confidence: float = 0.0



@dataclass
class DebateResult:
    """
    Stores complete investment committee debate.
    """

    company: Optional[str] = None

    participants: List[str] = field(
        default_factory=list
    )

    arguments: List[AnalystArgument] = field(
        default_factory=list
    )

    consensus: Dict[str, Any] = field(
        default_factory=dict
    )



@dataclass
class CommitteeDecision:
    """
    Final investment committee decision.
    """

    recommendation: str

    confidence_score: float

    thesis: str = ""

    risks: List[str] = field(
        default_factory=list
    )

    catalysts: List[str] = field(
        default_factory=list
    )

    supporting_votes: int = 0

    opposing_votes: int = 0



@dataclass
class InvestmentMemo:
    """
    Final output generated by
    Investment Committee Agent.

    Used by Report Builder.
    """

    company: str

    recommendation: str

    investment_thesis: str

    valuation_summary: str

    risk_summary: str

    catalyst_summary: str

    confidence: float

    evidence: List[Dict[str, Any]] = field(
        default_factory=list
    )