"use client";

import {
  Check,
  Clock3,
  Download,
  FileText,
  Loader,
  Pencil,
} from "lucide-react";

import { useMemo, useState } from "react";
import jsPDF from "jspdf";

import { cn, EmptyState } from "../../components/ui";

/*
 * ============================================================
 * REPORT SECTION TYPE
 * ============================================================
 */

interface ReportSection {
  id: string;
  title: string;
  content?: string | null;
  status: "complete" | "in-progress" | "waiting";
  lastUpdated?: string | null;
}

/*
 * ============================================================
 * PROPS
 * ============================================================
 */

interface ReportViewerProps {
  title: string;
  sections: ReportSection[];
}

/*
 * ============================================================
 * PDF CONSTANTS
 * ============================================================
 */

const PDF = {
  pageWidth: 210,
  pageHeight: 297,

  marginLeft: 18,
  marginRight: 18,

  marginTop: 22,
  marginBottom: 20,

  headerHeight: 12,
  footerHeight: 12,

  bodyFontSize: 10.2,
  bodyLineHeight: 5.2,

  heading1Size: 18,
  heading2Size: 14,
  heading3Size: 11.5,

  sectionTitleSize: 15,

  smallFontSize: 8,
  tinyFontSize: 7,

  paragraphSpacing: 4.5,

  bulletIndent: 6,
  bulletTextIndent: 11,

  primaryText: [24, 31, 42] as [number, number, number],
  secondaryText: [70, 78, 90] as [number, number, number],
  mutedText: [115, 123, 135] as [number, number, number],

  accent: [37, 99, 235] as [number, number, number],

  border: [220, 224, 230] as [number, number, number],

  surface: [248, 249, 251] as [number, number, number],

  white: [255, 255, 255] as [number, number, number],
};

/*
 * ============================================================
 * STATUS BADGE
 * ============================================================
 */

function StatusBadge({
  status,
}: {
  status: ReportSection["status"];
}) {
  if (status === "complete") {
    return (
      <span
        className={cn(
          "inline-flex items-center gap-1.5",
          "rounded-full border border-success/15",
          "bg-success/10 px-2 py-1",
          "text-[10px] font-medium uppercase tracking-wider",
          "font-mono text-success",
        )}
      >
        <Check className="h-3 w-3" />
        Complete
      </span>
    );
  }

  if (status === "in-progress") {
    return (
      <span
        className={cn(
          "inline-flex items-center gap-1.5",
          "rounded-full border border-accent/15",
          "bg-accent/10 px-2 py-1",
          "text-[10px] font-medium uppercase tracking-wider",
          "font-mono text-accent",
        )}
      >
        <Loader className="h-3 w-3 animate-spin" />
        Generating
      </span>
    );
  }

  return (
    <span
      className={cn(
        "inline-flex items-center gap-1.5",
        "rounded-full border border-border",
        "bg-bg-surface px-2 py-1",
        "text-[10px] font-medium uppercase tracking-wider",
        "font-mono text-text-faint",
      )}
    >
      <Clock3 className="h-3 w-3" />
      Waiting
    </span>
  );
}

/*
 * ============================================================
 * MARKDOWN / TEXT HELPERS
 * ============================================================
 */

/**
 * jsPDF's built-in fonts do not support every Unicode character.
 *
 * Normalize the common characters generated by LLMs so the
 * exported PDF remains readable instead of displaying boxes.
 */
function normalizePdfText(value: string): string {
  return value
    .replace(/\r\n/g, "\n")
    .replace(/\r/g, "\n")
    .replace(/[“”]/g, '"')
    .replace(/[‘’]/g, "'")
    .replace(/[–—]/g, "-")
    .replace(/…/g, "...")
    .replace(/•/g, "*")
    .replace(/→/g, "->")
    .replace(/←/g, "<-")
    .replace(/≥/g, ">=")
    .replace(/≤/g, "<=")
    .replace(/≠/g, "!=")
    .replace(/×/g, "x")
    .replace(/÷/g, "/")
    .replace(/\u00A0/g, " ")
    .replace(/[^\x09\x0A\x0D\x20-\x7E]/g, "");
}

/**
 * Remove markdown markers while preserving the readable text.
 */
function stripMarkdown(value: string): string {
  return normalizePdfText(value)
    .replace(/!\[([^\]]*)\]\([^)]+\)/g, "$1")
    .replace(/\[([^\]]+)\]\([^)]+\)/g, "$1")
    .replace(/`([^`]+)`/g, "$1")
    .replace(/\*\*\*([^*]+)\*\*\*/g, "$1")
    .replace(/\*\*([^*]+)\*\*/g, "$1")
    .replace(/__([^_]+)__/g, "$1")
    .replace(/\*([^*]+)\*/g, "$1")
    .replace(/_([^_]+)_/g, "$1")
    .trim();
}

function isMarkdownHeading(line: string) {
  return /^#{1,6}\s+/.test(line.trim());
}

function getMarkdownHeadingLevel(line: string): number {
  const match = line.trim().match(/^(#{1,6})\s+/);
  return match ? match[1].length : 0;
}

function isBullet(line: string) {
  return /^\s*[-*+]\s+/.test(line);
}

function isNumberedList(line: string) {
  return /^\s*\d+[.)]\s+/.test(line);
}

function isBlockQuote(line: string) {
  return /^\s*>\s?/.test(line);
}

function isHorizontalRule(line: string) {
  return /^\s*(-{3,}|\*{3,}|_{3,})\s*$/.test(line);
}

function cleanBullet(line: string) {
  return stripMarkdown(
    line.replace(/^\s*[-*+]\s+/, ""),
  );
}

function cleanNumberedList(line: string) {
  const match = line.match(
    /^\s*(\d+)[.)]\s+(.*)$/,
  );

  if (!match) {
    return stripMarkdown(line);
  }

  return {
    number: match[1],
    text: stripMarkdown(match[2]),
  };
}

/*
 * ============================================================
 * PDF RENDERING HELPERS
 * ============================================================
 */

interface PdfRenderer {
  pdf: jsPDF;
  y: number;
  pageNumber: number;
}

function contentWidth() {
  return (
    PDF.pageWidth -
    PDF.marginLeft -
    PDF.marginRight
  );
}

function availableBottom() {
  return (
    PDF.pageHeight -
    PDF.marginBottom -
    PDF.footerHeight
  );
}

/*
 * ============================================================
 * PAGE HEADER / FOOTER
 * ============================================================
 */

function drawPageHeader(
  renderer: PdfRenderer,
  title: string,
) {
  const { pdf } = renderer;

  pdf.setDrawColor(...PDF.border);
  pdf.setLineWidth(0.25);

  pdf.line(
    PDF.marginLeft,
    15,
    PDF.pageWidth - PDF.marginRight,
    15,
  );

  pdf.setFont("helvetica", "normal");
  pdf.setFontSize(PDF.tinyFontSize);
  pdf.setTextColor(...PDF.mutedText);

  pdf.text(
    normalizePdfText(title).toUpperCase(),
    PDF.marginLeft,
    10,
  );

  pdf.setTextColor(...PDF.accent);

  pdf.text(
    "RESEARCH REPORT",
    PDF.pageWidth - PDF.marginRight,
    10,
    {
      align: "right",
    },
  );
}

function drawPageFooter(
  renderer: PdfRenderer,
) {
  const { pdf, pageNumber } = renderer;

  const y =
    PDF.pageHeight -
    PDF.marginBottom +
    4;

  pdf.setDrawColor(...PDF.border);
  pdf.setLineWidth(0.25);

  pdf.line(
    PDF.marginLeft,
    y - 5,
    PDF.pageWidth - PDF.marginRight,
    y - 5,
  );

  pdf.setFont("helvetica", "normal");
  pdf.setFontSize(PDF.tinyFontSize);
  pdf.setTextColor(...PDF.mutedText);

  pdf.text(
    "AI RESEARCH ANALYSIS",
    PDF.marginLeft,
    y,
  );

  pdf.text(
    `Page ${pageNumber}`,
    PDF.pageWidth - PDF.marginRight,
    y,
    {
      align: "right",
    },
  );
}

/*
 * ============================================================
 * NEW PAGE
 * ============================================================
 */

function newPdfPage(
  renderer: PdfRenderer,
  title: string,
) {
  renderer.pdf.addPage();

  renderer.pageNumber += 1;

  drawPageHeader(
    renderer,
    title,
  );

  drawPageFooter(renderer);

  renderer.y =
    PDF.marginTop +
    PDF.headerHeight;
}

/*
 * ============================================================
 * ENSURE SPACE
 * ============================================================
 */

function ensurePdfSpace(
  renderer: PdfRenderer,
  requiredHeight: number,
  title: string,
) {
  if (
    renderer.y + requiredHeight <=
    availableBottom()
  ) {
    return;
  }

  newPdfPage(
    renderer,
    title,
  );
}

/*
 * ============================================================
 * DRAW WRAPPED TEXT
 * ============================================================
 */

function drawWrappedText(
  renderer: PdfRenderer,
  text: string,
  options?: {
    fontSize?: number;
    lineHeight?: number;
    fontStyle?: "normal" | "bold" | "italic";
    color?: [number, number, number];
    indent?: number;
    spacingAfter?: number;
    title?: string;
  },
) {
  const {
    pdf,
  } = renderer;

  const fontSize =
    options?.fontSize ??
    PDF.bodyFontSize;

  const lineHeight =
    options?.lineHeight ??
    PDF.bodyLineHeight;

  const fontStyle =
    options?.fontStyle ??
    "normal";

  const color =
    options?.color ??
    PDF.secondaryText;

  const indent =
    options?.indent ??
    0;

  const spacingAfter =
    options?.spacingAfter ??
    0;

  const title =
    options?.title ??
    "Research Report";

  const safeText =
    normalizePdfText(text).trim();

  if (!safeText) {
    return;
  }

  pdf.setFont(
    "helvetica",
    fontStyle,
  );

  pdf.setFontSize(fontSize);
  pdf.setTextColor(...color);

  const maxWidth =
    contentWidth() - indent;

  const lines =
    pdf.splitTextToSize(
      safeText,
      maxWidth,
    );

  for (const line of lines) {
    ensurePdfSpace(
      renderer,
      lineHeight,
      title,
    );

    pdf.text(
      line,
      PDF.marginLeft + indent,
      renderer.y,
    );

    renderer.y += lineHeight;
  }

  renderer.y += spacingAfter;
}

/*
 * ============================================================
 * DRAW SECTION HEADING
 * ============================================================
 */

function drawSectionHeading(
  renderer: PdfRenderer,
  title: string,
  number: number,
  reportTitle: string,
) {
  const {
    pdf,
  } = renderer;

  const headingHeight = 22;

  ensurePdfSpace(
    renderer,
    headingHeight,
    reportTitle,
  );

  pdf.setFillColor(...PDF.surface);

  pdf.roundedRect(
    PDF.marginLeft,
    renderer.y - 5,
    contentWidth(),
    17,
    2,
    2,
    "F",
  );

  pdf.setFillColor(...PDF.accent);

  pdf.roundedRect(
    PDF.marginLeft + 4,
    renderer.y - 1,
    6,
    6,
    1.5,
    1.5,
    "F",
  );

  pdf.setFont(
    "helvetica",
    "bold",
  );

  pdf.setFontSize(7);

  pdf.setTextColor(
    ...PDF.white,
  );

  pdf.text(
    String(number).padStart(
      2,
      "0",
    ),
    PDF.marginLeft + 7,
    renderer.y + 3.3,
    {
      align: "center",
    },
  );

  pdf.setFont(
    "helvetica",
    "bold",
  );

  pdf.setFontSize(
    PDF.sectionTitleSize,
  );

  pdf.setTextColor(
    ...PDF.primaryText,
  );

  const heading =
    stripMarkdown(title);

  pdf.text(
    heading,
    PDF.marginLeft + 14,
    renderer.y + 4,
  );

  renderer.y += 20;
}

/*
 * ============================================================
 * DRAW MARKDOWN HEADING
 * ============================================================
 */

function drawMarkdownHeading(
  renderer: PdfRenderer,
  text: string,
  level: number,
  reportTitle: string,
) {
  const {
    pdf,
  } = renderer;

  const clean =
    stripMarkdown(text);

  if (!clean) {
    return;
  }

  const size =
    level === 1
      ? PDF.heading1Size
      : level === 2
        ? PDF.heading2Size
        : PDF.heading3Size;

  const spacingBefore =
    level === 1
      ? 7
      : level === 2
        ? 6
        : 5;

  const spacingAfter =
    level === 1
      ? 6
      : level === 2
        ? 5
        : 4;

  ensurePdfSpace(
    renderer,
    size * 0.55 +
      spacingBefore +
      spacingAfter +
      8,
    reportTitle,
  );

  renderer.y +=
    spacingBefore;

  pdf.setFont(
    "helvetica",
    "bold",
  );

  pdf.setFontSize(size);

  pdf.setTextColor(
    ...PDF.primaryText,
  );

  const lines =
    pdf.splitTextToSize(
      clean,
      contentWidth(),
    );

  for (const line of lines) {
    ensurePdfSpace(
      renderer,
      size * 0.55,
      reportTitle,
    );

    pdf.text(
      line,
      PDF.marginLeft,
      renderer.y,
    );

    renderer.y +=
      size * 0.55;
  }

  if (level === 1) {
    pdf.setDrawColor(
      ...PDF.accent,
    );

    pdf.setLineWidth(0.5);

    pdf.line(
      PDF.marginLeft,
      renderer.y + 1,
      PDF.marginLeft + 20,
      renderer.y + 1,
    );
  }

  renderer.y +=
    spacingAfter;
}

/*
 * ============================================================
 * DRAW BULLET
 * ============================================================
 */

function drawBullet(
  renderer: PdfRenderer,
  text: string,
  reportTitle: string,
) {
  const {
    pdf,
  } = renderer;

  const safeText =
    cleanBullet(text);

  if (!safeText) {
    return;
  }

  const textWidth =
    contentWidth() -
    PDF.bulletTextIndent;

  pdf.setFont(
    "helvetica",
    "normal",
  );

  pdf.setFontSize(
    PDF.bodyFontSize,
  );

  const lines =
    pdf.splitTextToSize(
      safeText,
      textWidth,
    );

  const totalHeight =
    lines.length *
    PDF.bodyLineHeight;

  ensurePdfSpace(
    renderer,
    totalHeight,
    reportTitle,
  );

  pdf.setFillColor(
    ...PDF.accent,
  );

  pdf.circle(
    PDF.marginLeft +
      2,
    renderer.y - 1.4,
    0.9,
    "F",
  );

  pdf.setTextColor(
    ...PDF.secondaryText,
  );

  lines.forEach(
    (
      line: string,
      index: number,
    ) => {
      if (index > 0) {
        ensurePdfSpace(
          renderer,
          PDF.bodyLineHeight,
          reportTitle,
        );
      }

      pdf.text(
        line,
        PDF.marginLeft +
          PDF.bulletTextIndent,
        renderer.y,
      );

      renderer.y +=
        PDF.bodyLineHeight;
    },
  );

  renderer.y += 1.5;
}

/*
 * ============================================================
 * DRAW NUMBERED ITEM
 * ============================================================
 */

function drawNumberedItem(
  renderer: PdfRenderer,
  line: string,
  reportTitle: string,
) {
  const {
    pdf,
  } = renderer;

  const parsed =
    cleanNumberedList(line);

  const textWidth =
    contentWidth() -
    PDF.bulletTextIndent;

  pdf.setFont(
    "helvetica",
    "normal",
  );

  pdf.setFontSize(
    PDF.bodyFontSize,
  );

  const lines =
    pdf.splitTextToSize(
      parsed.text,
      textWidth,
    );

  const totalHeight =
    lines.length *
    PDF.bodyLineHeight;

  ensurePdfSpace(
    renderer,
    totalHeight,
    reportTitle,
  );

  pdf.setFont(
    "helvetica",
    "bold",
  );

  pdf.setTextColor(
    ...PDF.accent,
  );

  pdf.text(
    `${parsed.number}.`,
    PDF.marginLeft,
    renderer.y,
  );

  pdf.setFont(
    "helvetica",
    "normal",
  );

  pdf.setTextColor(
    ...PDF.secondaryText,
  );

  lines.forEach(
    (
      textLine: string,
      index: number,
    ) => {
      if (index > 0) {
        ensurePdfSpace(
          renderer,
          PDF.bodyLineHeight,
          reportTitle,
        );
      }

      pdf.text(
        textLine,
        PDF.marginLeft +
          PDF.bulletTextIndent,
        renderer.y,
      );

      renderer.y +=
        PDF.bodyLineHeight;
    },
  );

  renderer.y += 1.5;
}

/*
 * ============================================================
 * DRAW BLOCKQUOTE
 * ============================================================
 */

function drawBlockQuote(
  renderer: PdfRenderer,
  line: string,
  reportTitle: string,
) {
  const {
    pdf,
  } = renderer;

  const text =
    stripMarkdown(
      line.replace(
        /^\s*>\s?/,
        "",
      ),
    );

  const indent = 7;

  pdf.setFont(
    "helvetica",
    "italic",
  );

  pdf.setFontSize(
    PDF.bodyFontSize,
  );

  const lines =
    pdf.splitTextToSize(
      text,
      contentWidth() - indent,
    );

  ensurePdfSpace(
    renderer,
    lines.length *
      PDF.bodyLineHeight +
      4,
    reportTitle,
  );

  const startY =
    renderer.y;

  pdf.setTextColor(
    ...PDF.secondaryText,
  );

  lines.forEach(
    (
      textLine: string,
    ) => {
      pdf.text(
        textLine,
        PDF.marginLeft +
          indent,
        renderer.y,
      );

      renderer.y +=
        PDF.bodyLineHeight;
    },
  );

  pdf.setDrawColor(
    ...PDF.accent,
  );

  pdf.setLineWidth(1);

  pdf.line(
    PDF.marginLeft,
    startY - 3,
    PDF.marginLeft,
    renderer.y - 1,
  );

  renderer.y += 3;
}

/*
 * ============================================================
 * DRAW REPORT CONTENT
 * ============================================================
 */

function drawReportContent(
  renderer: PdfRenderer,
  content: string,
  reportTitle: string,
) {
  const normalized =
    normalizePdfText(content);

  const lines =
    normalized.split("\n");

  let paragraphLines: string[] = [];

  const flushParagraph =
    () => {
      if (
        paragraphLines.length === 0
      ) {
        return;
      }

      const paragraph =
        paragraphLines
          .join(" ")
          .replace(
            /\s+/g,
            " ",
          )
          .trim();

      if (paragraph) {
        drawWrappedText(
          renderer,
          stripMarkdown(
            paragraph,
          ),
          {
            fontSize:
              PDF.bodyFontSize,
            lineHeight:
              PDF.bodyLineHeight,
            color:
              PDF.secondaryText,
            spacingAfter:
              PDF.paragraphSpacing,
            title:
              reportTitle,
          },
        );
      }

      paragraphLines = [];
    };

  for (
    let index = 0;
    index < lines.length;
    index += 1
  ) {
    const rawLine =
      lines[index] ?? "";

    const trimmed =
      rawLine.trim();

    /*
     * Blank line.
     */

    if (!trimmed) {
      flushParagraph();
      renderer.y += 1;
      continue;
    }

    /*
     * Horizontal rule.
     */

    if (
      isHorizontalRule(
        trimmed,
      )
    ) {
      flushParagraph();

      ensurePdfSpace(
        renderer,
        7,
        reportTitle,
      );

      renderer.pdf.setDrawColor(
        ...PDF.border,
      );

      renderer.pdf.setLineWidth(
        0.3,
      );

      renderer.pdf.line(
        PDF.marginLeft,
        renderer.y,
        PDF.pageWidth -
          PDF.marginRight,
        renderer.y,
      );

      renderer.y += 6;

      continue;
    }

    /*
     * Markdown heading.
     */

    if (
      isMarkdownHeading(
        trimmed,
      )
    ) {
      flushParagraph();

      const level =
        getMarkdownHeadingLevel(
          trimmed,
        );

      const heading =
        trimmed.replace(
          /^#{1,6}\s+/,
          "",
        );

      drawMarkdownHeading(
        renderer,
        heading,
        level,
        reportTitle,
      );

      continue;
    }

    /*
     * Bullet.
     */

    if (
      isBullet(trimmed)
    ) {
      flushParagraph();

      drawBullet(
        renderer,
        trimmed,
        reportTitle,
      );

      continue;
    }

    /*
     * Numbered list.
     */

    if (
      isNumberedList(
        trimmed,
      )
    ) {
      flushParagraph();

      drawNumberedItem(
        renderer,
        trimmed,
        reportTitle,
      );

      continue;
    }

    /*
     * Blockquote.
     */

    if (
      isBlockQuote(trimmed)
    ) {
      flushParagraph();

      drawBlockQuote(
        renderer,
        trimmed,
        reportTitle,
      );

      continue;
    }

    /*
     * Otherwise this is part of a paragraph.
     */

    paragraphLines.push(
      trimmed,
    );
  }

  flushParagraph();
}

/*
 * ============================================================
 * COVER PAGE
 * ============================================================
 */

function drawCoverPage(
  renderer: PdfRenderer,
  title: string,
  completedCount: number,
  totalCount: number,
) {
  const {
    pdf,
  } = renderer;

  /*
   * Accent marker.
   */

  pdf.setFillColor(
    ...PDF.accent,
  );

  pdf.roundedRect(
    PDF.marginLeft,
    32,
    7,
    7,
    2,
    2,
    "F",
  );

  /*
   * Label.
   */

  pdf.setFont(
    "helvetica",
    "bold",
  );

  pdf.setFontSize(8);

  pdf.setTextColor(
    ...PDF.accent,
  );

  pdf.text(
    "RESEARCH REPORT",
    PDF.marginLeft + 12,
    37,
  );

  /*
   * Main title.
   */

  pdf.setFont(
    "helvetica",
    "bold",
  );

  pdf.setFontSize(26);

  pdf.setTextColor(
    ...PDF.primaryText,
  );

  const titleLines =
    pdf.splitTextToSize(
      normalizePdfText(title),
      contentWidth(),
    );

  let titleY = 70;

  titleLines.forEach(
    (line: string) => {
      pdf.text(
        line,
        PDF.marginLeft,
        titleY,
      );

      titleY += 12;
    },
  );

  /*
   * Description.
   */

  pdf.setFont(
    "helvetica",
    "normal",
  );

  pdf.setFontSize(11);

  pdf.setTextColor(
    ...PDF.secondaryText,
  );

  const description =
    "Comprehensive analysis generated from the completed research pipeline.";

  const descriptionLines =
    pdf.splitTextToSize(
      description,
      contentWidth(),
    );

  let descriptionY =
    titleY + 10;

  descriptionLines.forEach(
    (line: string) => {
      pdf.text(
        line,
        PDF.marginLeft,
        descriptionY,
      );

      descriptionY += 6;
    },
  );

  /*
   * Metadata block.
   */

  const cardY =
    descriptionY + 18;

  pdf.setFillColor(
    ...PDF.surface,
  );

  pdf.roundedRect(
    PDF.marginLeft,
    cardY,
    contentWidth(),
    44,
    3,
    3,
    "F",
  );

  pdf.setFont(
    "helvetica",
    "bold",
  );

  pdf.setFontSize(8);

  pdf.setTextColor(
    ...PDF.mutedText,
  );

  pdf.text(
    "REPORT STATUS",
    PDF.marginLeft + 8,
    cardY + 10,
  );

  pdf.setFont(
    "helvetica",
    "bold",
  );

  pdf.setFontSize(12);

  pdf.setTextColor(
    ...PDF.primaryText,
  );

  pdf.text(
    `${completedCount} of ${totalCount} sections complete`,
    PDF.marginLeft + 8,
    cardY + 19,
  );

  pdf.setFont(
    "helvetica",
    "normal",
  );

  pdf.setFontSize(8);

  pdf.setTextColor(
    ...PDF.mutedText,
  );

  pdf.text(
    "Generated research analysis",
    PDF.marginLeft + 8,
    cardY + 30,
  );

  /*
   * Bottom brand.
   */

  pdf.setFont(
    "helvetica",
    "normal",
  );

  pdf.setFontSize(8);

  pdf.setTextColor(
    ...PDF.mutedText,
  );

  pdf.text(
    "AI RESEARCH ANALYSIS",
    PDF.marginLeft,
    PDF.pageHeight - 24,
  );

  pdf.text(
    `Page ${renderer.pageNumber}`,
    PDF.pageWidth -
      PDF.marginRight,
    PDF.pageHeight - 24,
    {
      align: "right",
    },
  );

  /*
   * Bottom line.
   */

  pdf.setDrawColor(
    ...PDF.border,
  );

  pdf.setLineWidth(0.3);

  pdf.line(
    PDF.marginLeft,
    PDF.pageHeight - 18,
    PDF.pageWidth -
      PDF.marginRight,
    PDF.pageHeight - 18,
  );
}

/*
 * ============================================================
 * EXPORT PDF
 * ============================================================
 */

async function createResearchPdf(
  title: string,
  sections: ReportSection[],
) {
  const pdf =
    new jsPDF({
      orientation: "portrait",
      unit: "mm",
      format: "a4",
      compress: true,
      putOnlyUsedFonts: true,
    });

  const safeSections =
    Array.isArray(sections)
      ? sections
      : [];

  const completedSections =
    safeSections.filter(
      (section) =>
        section.status ===
          "complete" &&
        typeof section.content ===
          "string" &&
        section.content.trim(),
    );

  const renderer: PdfRenderer =
    {
      pdf,
      y: PDF.marginTop,
      pageNumber: 1,
    };

  /*
   * ==========================================================
   * COVER PAGE
   * ==========================================================
   */

  drawCoverPage(
    renderer,
    title,
    completedSections.length,
    safeSections.length,
  );

  /*
   * ==========================================================
   * REPORT SECTIONS
   * ==========================================================
   */

  completedSections.forEach(
    (
      section,
      index,
    ) => {
      /*
       * Every major report section starts on a fresh page.
       *
       * This gives us predictable professional pagination
       * instead of squeezing sections into arbitrary canvas
       * dimensions.
       */

      newPdfPage(
        renderer,
        title,
      );

      drawSectionHeading(
        renderer,
        section.title,
        index + 1,
        title,
      );

      drawReportContent(
        renderer,
        section.content ?? "",
        title,
      );

      /*
       * Section separator.
       */

      if (
        index <
        completedSections.length - 1
      ) {
        renderer.y += 3;
      }
    },
  );

  /*
   * ==========================================================
   * FINAL PAGE FOOTERS
   *
   * Headers/footers are already drawn when pages are created.
   * ==========================================================
   */

  /*
   * ==========================================================
   * FILE NAME
   * ==========================================================
   */

  const safeTitle =
    normalizePdfText(
      title ||
        "Research Report",
    )
      .replace(
        /[^a-z0-9-_]+/gi,
        "-",
      )
      .replace(
        /-+/g,
        "-",
      )
      .replace(
        /^-|-$/g,
        "",
      );

  const fileName =
    `${
      safeTitle ||
      "Research-Report"
    }-Research-Report.pdf`;

  pdf.save(fileName);

  return fileName;
}

/*
 * ============================================================
 * REPORT VIEWER
 * ============================================================
 */

export function ReportViewer({
  title,
  sections,
}: ReportViewerProps) {
  const [isExporting, setIsExporting] =
    useState(false);

  /*
   * ==========================================================
   * SAFE DATA
   * ==========================================================
   */

  const safeSections =
    Array.isArray(sections)
      ? sections
      : [];

  const completedSections =
    useMemo(
      () =>
        safeSections.filter(
          (section) =>
            section.status ===
              "complete" &&
            typeof section.content ===
              "string" &&
            Boolean(
              section.content.trim(),
            ),
        ),
      [safeSections],
    );

  const hasContent =
    completedSections.length > 0;

  const allWaiting =
    safeSections.length > 0 &&
    safeSections.every(
      (section) =>
        section.status ===
        "waiting",
    );

  const hasInProgress =
    safeSections.some(
      (section) =>
        section.status ===
        "in-progress",
    );

  /*
   * ==========================================================
   * EXPORT
   * ==========================================================
   */

  const exportPDF =
    async () => {
      if (
        isExporting ||
        !hasContent
      ) {
        return;
      }

      try {
        setIsExporting(true);

        /*
         * Give React one tick before beginning the export.
         * This makes the button state update immediately.
         */

        await new Promise<void>(
          (resolve) =>
            requestAnimationFrame(
              () => resolve(),
            ),
        );

        await createResearchPdf(
          title,
          completedSections,
        );

        console.info(
          "Research report PDF exported successfully.",
        );
      } catch (error) {
        console.error(
          "Failed to export research report:",
          error,
        );

        const message =
          error instanceof Error
            ? error.message
            : "Unknown PDF export error.";

        window.alert(
          `Failed to export the research report.\n\n${message}`,
        );
      } finally {
        setIsExporting(false);
      }
    };

  /*
   * ==========================================================
   * RENDER
   * ==========================================================
   */

  return (
    <div className="w-full">
      {/* ======================================================
       * PAGE HEADER
       * ====================================================== */}

      <div
        className={cn(
          "mb-6 flex flex-col gap-4",
          "sm:flex-row sm:items-center sm:justify-between",
          "px-1",
        )}
      >
        <div className="min-w-0">
          <div className="flex items-center gap-2.5">
            <div
              className={cn(
                "flex h-9 w-9 shrink-0",
                "items-center justify-center",
                "rounded-lg",
                "border border-accent/15",
                "bg-accent/10",
              )}
            >
              <FileText className="h-4 w-4 text-accent" />
            </div>

            <div className="min-w-0">
              <h2 className="truncate text-lg font-semibold text-text-primary">
                {title}
              </h2>

              <p className="mt-0.5 text-xs text-text-muted">
                AI research report
              </p>
            </div>
          </div>
        </div>

        {/* ====================================================
         * EXPORT BUTTON
         * ==================================================== */}

        <button
          type="button"
          onClick={exportPDF}
          disabled={
            isExporting ||
            !hasContent
          }
          aria-busy={
            isExporting
          }
          className={cn(
            "inline-flex shrink-0",
            "items-center justify-center gap-2",
            "rounded-lg",
            "border border-accent/20",
            "bg-accent/10",
            "px-3.5 py-2",
            "text-sm font-medium text-accent",
            "transition-all duration-200",
            "hover:border-accent/30",
            "hover:bg-accent/15",
            "active:scale-[0.98]",
            "disabled:cursor-not-allowed",
            "disabled:opacity-40",
          )}
        >
          <Download
            className={cn(
              "h-3.5 w-3.5",
              isExporting &&
                "animate-pulse",
            )}
          />

          {isExporting
            ? "Generating..."
            : "Export PDF"}
        </button>
      </div>

      {/* ======================================================
       * REPORT DOCUMENT
       * ====================================================== */}

      <div
        className={cn(
          "mx-auto w-full",
          "overflow-hidden",
          "rounded-xl",
          "border border-border",
          "bg-white",
          "shadow-sm",
        )}
      >
        {/* ====================================================
         * REPORT DOCUMENT HEADER
         * ==================================================== */}

        <div
          className={cn(
            "border-b border-border",
            "px-5 py-5",
            "sm:px-7 sm:py-6",
          )}
        >
          <div className="mb-2 flex items-center gap-2">
            <span
              className={cn(
                "h-1.5 w-1.5 rounded-full",
                "bg-accent",
              )}
            />

            <span className="font-mono text-[10px] uppercase tracking-[0.18em] text-text-faint">
              Research Report
            </span>
          </div>

          <h1 className="text-xl font-semibold tracking-tight text-text-primary sm:text-2xl">
            {title}
          </h1>

          <p className="mt-2 max-w-2xl text-sm leading-relaxed text-text-muted">
            Comprehensive analysis generated from the
            completed research pipeline.
          </p>
        </div>

        {/* ====================================================
         * EMPTY STATE
         * ==================================================== */}

        {!hasContent &&
        safeSections.length ===
          0 ? (
          <div className="p-6 sm:p-10">
            <EmptyState
              icon={
                <FileText className="h-5 w-5" />
              }
              title="No report sections available"
              description="The research completed, but no report sections were returned by the backend."
            />
          </div>
        ) : !hasContent &&
          allWaiting ? (
          <div className="p-6 sm:p-10">
            <EmptyState
              icon={
                <Clock3 className="h-5 w-5" />
              }
              title="Report generation hasn't started"
              description="Report sections will appear here as the AI completes each stage of analysis."
            />
          </div>
        ) : (
          <div className="divide-y divide-border">
            {safeSections.map(
              (
                section,
                sectionIndex,
              ) => {
                const content =
                  typeof section.content ===
                  "string"
                    ? section.content.trim()
                    : "";

                return (
                  <article
                    key={section.id}
                    className={cn(
                      "px-5 py-6",
                      "sm:px-7 sm:py-7",
                      "transition-colors",
                      section.status ===
                        "in-progress" &&
                        "bg-accent/[0.025]",
                    )}
                  >
                    {/* ======================================
                     * SECTION HEADER
                     * ====================================== */}

                    <div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
                      <div className="flex min-w-0 items-start gap-3">
                        <div
                          className={cn(
                            "mt-0.5 flex h-7 w-7 shrink-0",
                            "items-center justify-center",
                            "rounded-md",
                            "border border-border",
                            "bg-bg-surface",
                            "font-mono text-[10px]",
                            "text-text-faint",
                          )}
                        >
                          {String(
                            sectionIndex +
                              1,
                          ).padStart(
                            2,
                            "0",
                          )}
                        </div>

                        <div className="min-w-0">
                          <h3 className="text-sm font-semibold text-text-primary sm:text-base">
                            {section.title}
                          </h3>

                          {section.status ===
                            "in-progress" && (
                            <p className="mt-1 text-xs text-text-muted">
                              AI is currently
                              generating this
                              section.
                            </p>
                          )}
                        </div>
                      </div>

                      <StatusBadge
                        status={
                          section.status
                        }
                      />
                    </div>

                    {/* ======================================
                     * SECTION CONTENT
                     * ====================================== */}

                    {content ? (
                      <div className="mt-5 pl-0 sm:pl-10">
                        <div className="space-y-3">
                          {content
                            .split(
                              "\n",
                            )
                            .map(
                              (
                                line,
                                index,
                              ) => {
                                const trimmed =
                                  line.trim();

                                if (
                                  !trimmed
                                ) {
                                  return (
                                    <div
                                      key={
                                        index
                                      }
                                      className="h-1"
                                    />
                                  );
                                }

                                const isHeading =
                                  trimmed.startsWith(
                                    "#",
                                  ) ||
                                  (trimmed.endsWith(
                                    ":",
                                  ) &&
                                    trimmed.length <
                                      120);

                                return (
                                  <p
                                    key={
                                      index
                                    }
                                    className={cn(
                                      "leading-7",
                                      isHeading
                                        ? "text-sm font-semibold text-text-primary"
                                        : "text-sm text-text-secondary",
                                    )}
                                  >
                                    {
                                      trimmed
                                    }
                                  </p>
                                );
                              },
                            )}
                        </div>
                      </div>
                    ) : (
                      <div
                        className={cn(
                          "mt-5",
                          "rounded-lg",
                          "border border-dashed border-border",
                          "bg-bg-surface/50",
                          "px-4 py-6",
                          "text-center",
                        )}
                      >
                        {section.status ===
                        "in-progress" ? (
                          <>
                            <Loader className="mx-auto h-4 w-4 animate-spin text-accent" />

                            <p className="mt-2 text-xs text-text-muted">
                              Generating
                              section...
                            </p>
                          </>
                        ) : (
                          <p className="text-xs italic text-text-faint">
                            This section does
                            not have content
                            yet.
                          </p>
                        )}
                      </div>
                    )}

                    {/* ======================================
                     * SECTION FOOTER
                     * ====================================== */}

                    {content &&
                      section.status ===
                        "complete" && (
                        <div
                          className={cn(
                            "mt-5 flex flex-wrap",
                            "items-center gap-3",
                            "border-t border-border-subtle",
                            "pt-3",
                            "sm:pl-10",
                          )}
                        >
                          <button
                            type="button"
                            disabled
                            title="Editing will be available soon"
                            className={cn(
                              "inline-flex items-center gap-1.5",
                              "cursor-not-allowed",
                              "text-[11px]",
                              "text-text-faint",
                              "opacity-70",
                            )}
                          >
                            <Pencil className="h-3 w-3" />
                            Edit
                          </button>

                          {section.lastUpdated && (
                            <span className="ml-auto font-mono text-[10px] text-text-faint">
                              Updated{" "}
                              {
                                section.lastUpdated
                              }
                            </span>
                          )}
                        </div>
                      )}
                  </article>
                );
              },
            )}
          </div>
        )}

        {/* ====================================================
         * GENERATION FOOTER
         * ==================================================== */}

        {hasInProgress && (
          <div
            className={cn(
              "flex items-center gap-2",
              "border-t border-border",
              "bg-accent/[0.025]",
              "px-5 py-3",
              "sm:px-7",
            )}
          >
            <Loader className="h-3.5 w-3.5 animate-spin text-accent" />

            <span className="text-[11px] text-text-muted">
              Research is still being generated.
              This report will update automatically.
            </span>
          </div>
        )}
      </div>
    </div>
  );
}