"""initial schema

Revision ID: 6f9ed2cf9a9f
Revises: 
Create Date: 2026-08-23 18:11:57.519323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f9ed2cf9a9f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=True),
    sa.Column('ticker', sa.String(length=20), nullable=True),
    sa.Column('exchange', sa.String(length=50), nullable=True),
    sa.Column('cik', sa.String(length=20), nullable=True),
    sa.Column('lei', sa.String(length=25), nullable=True),
    sa.Column('sector', sa.String(length=150), nullable=True),
    sa.Column('industry', sa.String(length=150), nullable=True),
    sa.Column('sub_industry', sa.String(length=150), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('headquarters', sa.String(length=255), nullable=True),
    sa.Column('founded_year', sa.Integer(), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.String(length=1000), nullable=True),
    sa.Column('search_aliases', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lei')
    )
    op.create_index(op.f('ix_companies_cik'), 'companies', ['cik'], unique=True)
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_index(op.f('ix_companies_industry'), 'companies', ['industry'], unique=False)
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=False)
    op.create_index(op.f('ix_companies_sector'), 'companies', ['sector'], unique=False)
    op.create_index(op.f('ix_companies_ticker'), 'companies', ['ticker'], unique=True)
    op.create_table('industries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False, comment='Canonical internal industry code.'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Canonical industry name.'),
    sa.Column('slug', sa.String(length=255), nullable=False, comment='URL-safe normalized industry identifier.'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), server_default='0', nullable=False, comment='Hierarchy depth. 0 represents a top-level industry.'),
    sa.Column('sic_code', sa.String(length=20), nullable=True),
    sa.Column('naics_code', sa.String(length=20), nullable=True),
    sa.Column('gics_code', sa.String(length=20), nullable=True),
    sa.Column('icb_code', sa.String(length=20), nullable=True),
    sa.Column('sector', sa.String(length=255), nullable=True, comment='Optional external sector classification. Sector is not the canonical industry identity.'),
    sa.Column('metadata_json', sa.JSON(), server_default='{}', nullable=False, comment='Normalized industry metadata. Must not replace canonical industry fields.'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('level >= 0', name='ck_industries_level_nonnegative'),
    sa.ForeignKeyConstraint(['parent_id'], ['industries.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_industries_code'),
    sa.UniqueConstraint('slug', name='uq_industries_slug')
    )
    op.create_index('ix_industries_active', 'industries', ['is_active'], unique=False)
    op.create_index('ix_industries_gics_code', 'industries', ['gics_code'], unique=False)
    op.create_index('ix_industries_icb_code', 'industries', ['icb_code'], unique=False)
    op.create_index('ix_industries_naics_code', 'industries', ['naics_code'], unique=False)
    op.create_index('ix_industries_name', 'industries', ['name'], unique=False)
    op.create_index('ix_industries_parent_id', 'industries', ['parent_id'], unique=False)
    op.create_index('ix_industries_sector', 'industries', ['sector'], unique=False)
    op.create_index('ix_industries_sic_code', 'industries', ['sic_code'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('industry_classification_sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('industry_id', sa.Integer(), nullable=False),
    sa.Column('classification_system', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['industry_id'], ['industries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('industry_id', 'classification_system', 'code', name='uq_industry_classification_source')
    )
    op.create_index('ix_industry_classification_sources_code', 'industry_classification_sources', ['code'], unique=False)
    op.create_index('ix_industry_classification_sources_industry_id', 'industry_classification_sources', ['industry_id'], unique=False)
    op.create_index('ix_industry_classification_sources_system', 'industry_classification_sources', ['classification_system'], unique=False)
    op.create_table('industry_metadata',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('industry_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('value_json', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['industry_id'], ['industries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_industry_metadata_industry_id', 'industry_metadata', ['industry_id'], unique=False)
    op.create_index('ix_industry_metadata_key', 'industry_metadata', ['key'], unique=False)
    op.create_index('ix_industry_metadata_source', 'industry_metadata', ['source'], unique=False)
    op.create_table('research',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('intent', sa.String(length=100), nullable=False),
    sa.Column('research_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('ticker', sa.String(length=25), nullable=True),
    sa.Column('industry', sa.String(length=255), nullable=True),
    sa.Column('execution_plan_id', sa.String(length=100), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_id'), 'research', ['id'], unique=False)
    op.create_index(op.f('ix_research_intent'), 'research', ['intent'], unique=False)
    op.create_index(op.f('ix_research_research_type'), 'research', ['research_type'], unique=False)
    op.create_index(op.f('ix_research_status'), 'research', ['status'], unique=False)
    op.create_index(op.f('ix_research_ticker'), 'research', ['ticker'], unique=False)
    op.create_index(op.f('ix_research_user_id'), 'research', ['user_id'], unique=False)
    op.create_table('research_execution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('research_id', sa.Integer(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('current_agent', sa.String(length=100), nullable=True),
    sa.Column('current_task', sa.String(length=255), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['research_id'], ['research.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_execution_research_id'), 'research_execution', ['research_id'], unique=False)
    op.create_table('research_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('research_id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('sections', sa.JSON(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['research_id'], ['research.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_results_id'), 'research_results', ['id'], unique=False)
    op.create_index(op.f('ix_research_results_research_id'), 'research_results', ['research_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_research_results_research_id'), table_name='research_results')
    op.drop_index(op.f('ix_research_results_id'), table_name='research_results')
    op.drop_table('research_results')
    op.drop_index(op.f('ix_research_execution_research_id'), table_name='research_execution')
    op.drop_table('research_execution')
    op.drop_index(op.f('ix_research_user_id'), table_name='research')
    op.drop_index(op.f('ix_research_ticker'), table_name='research')
    op.drop_index(op.f('ix_research_status'), table_name='research')
    op.drop_index(op.f('ix_research_research_type'), table_name='research')
    op.drop_index(op.f('ix_research_intent'), table_name='research')
    op.drop_index(op.f('ix_research_id'), table_name='research')
    op.drop_table('research')
    op.drop_index('ix_industry_metadata_source', table_name='industry_metadata')
    op.drop_index('ix_industry_metadata_key', table_name='industry_metadata')
    op.drop_index('ix_industry_metadata_industry_id', table_name='industry_metadata')
    op.drop_table('industry_metadata')
    op.drop_index('ix_industry_classification_sources_system', table_name='industry_classification_sources')
    op.drop_index('ix_industry_classification_sources_industry_id', table_name='industry_classification_sources')
    op.drop_index('ix_industry_classification_sources_code', table_name='industry_classification_sources')
    op.drop_table('industry_classification_sources')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_industries_sic_code', table_name='industries')
    op.drop_index('ix_industries_sector', table_name='industries')
    op.drop_index('ix_industries_parent_id', table_name='industries')
    op.drop_index('ix_industries_name', table_name='industries')
    op.drop_index('ix_industries_naics_code', table_name='industries')
    op.drop_index('ix_industries_icb_code', table_name='industries')
    op.drop_index('ix_industries_gics_code', table_name='industries')
    op.drop_index('ix_industries_active', table_name='industries')
    op.drop_table('industries')
    op.drop_index(op.f('ix_companies_ticker'), table_name='companies')
    op.drop_index(op.f('ix_companies_sector'), table_name='companies')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_industry'), table_name='companies')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_index(op.f('ix_companies_cik'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
