"""
Planner Agent Models

Data structures used by the Planner Agent.
"""

from typing import List, Dict, Optional
from pydantic import BaseModel, Field


class ResearchRequest(BaseModel):
    """
    Incoming investor research request.
    """

    query: str = Field(
        ...,
        description="Investor research question"
    )

    company: Optional[str] = None

    research_type: Optional[str] = None

    depth: str = Field(
        default="institutional",
        description="Research depth level"
    )


class ResearchObjective(BaseModel):
    """
    Planner Agent interpretation of the request.
    """

    objective: str

    company: Optional[str] = None

    analysis_required: List[str] = []

    reasoning: Optional[str] = None


class PlannerTask(BaseModel):
    """
    Task generated by Planner Agent.
    """

    task_id: str

    agent: str

    description: str

    priority: str = "medium"

    dependencies: List[str] = []


class PlannerResponse(BaseModel):
    """
    Output returned by Planner Agent.
    """

    objective: ResearchObjective

    tasks: List[PlannerTask]

    metadata: Dict = {}